### ISSUE TITLE
ENH: HID over GATT for BLE Gamepads, Mice, Keyboards

### ISSUE THREAD

**Issue by westurner** [STMicroelectronics/X-CUBE-BLE1#1]
STORY: Users can use Bluetooth BLE Gamepads, Mice, and Keyboards with HID over GATT.

- [ ] HID over GATT
  - [ ] bluenrg_gatt_hid.c?
    https://github.com/STMicroelectronics/x-cube-ble1/blob/main/Middlewares/ST/BlueNRG-MS/hci/controller/bluenrg_gatt_aci.c
  - [ ] Support for Bluetooth BLE Gamepads
  - [ ] Support for Bluetooth BLE Keyboards and Mice
- [ ] For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus) or in the [ST Community/Q&A Topics](https://community.st.com/s/topiccatalog).

**Describe the set-up**

 * The board (either ST RPN reference or your custom board).
   * LEGO Hubs w/ pybricks-micropython (and pybricks over W3C WebBluetooth, or `pybricksdev` over BLE)
     * https://github.com/pybricks/pybricks-micropython/tree/master/lib/BlueNRG-MS
       * https://github.com/pybricks/pybricks-micropython/blob/master/3RD_PARTY_NOTICES.md#stm32-bluenrg-ms
 * IDE or at least the compiler and its version.
   * Haven't need to compile, though FWIW:
     * xeus-cling
     * https://github.com/quobit/awesome-python-in-education/issues/50
     * https://github.com/adafruit/circuitpython_jupyter_kernel#documentation
     * https://github.com/Carglglz/jupyter_upydevice_kernel
     * https://github.com/pybricks/pybricks-micropython/blob/master/.github/workflows/build.yml
     * https://github.com/wokwi/rp2040js

**Additional context**
From https://github.com/pybricks/support/issues/262 :

> ```
>           Does there need to be a *gamepad* Bluetooth HID in the pybricks firmware?
> ```
> 
> * [Please add BLEHID gamepad support and example adafruit/Adafruit_nRF52_Arduino#228 (comment)](https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/228#issuecomment-463191651))
>   
>   * https://github.com/sparkfun/circuitpython/blob/673d2fb4b7c5e077fc5579af1d249438d17d93ad/tools/hid_report_descriptors.py#L177-L207
>   * https://github.com/sparkfun/circuitpython/blob/673d2fb4b7c5e077fc5579af1d249438d17d93ad/tools/hid_report_descriptors.py#L246-L276
>   * https://learn.adafruit.com/custom-hid-devices-in-circuitpython?view=all#report-descriptors-3103536
>   * https://github.com/lemmingDev/ESP32-BLE-Gamepad
>   * https://github.com/DJm00n/ControllersInfo -- HID profiles for Xbox 360, Xbox One, PS4, PS4,  Stadia, and Switch    
>   * "HID over GATT Profile (HOGP) 1.0" https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=245141 :
>     > **1 Introduction**
>     > The HID over GATT profile defines the procedures and features to be used by Bluetooth
>     > low energy HID Devices using GATT and Bluetooth HID Hosts using GATT.
>     > This profile is an adaptation of the USB HID specification [2] to operate over a Bluetooth low energy wireless link.
>     > This profile shall operate over an LE transport only. For BR/EDR, the Bluetooth Human Interface Device Profile Specification [9] shall be used.
>     > **1.1 Profile Dependencies**
>     > This profile requires the Generic Attribute Profile (GATT), the Battery Service, the Device Information Service, and the Scan Parameters Profile.
>     > This specification can be used with Bluetooth Core Specification Version 4.0 [3] or later.

**Screenshots**

**Comment by silviooliva** [comment]
Hello @westurner,
for the BLE HID profile, you could have a look at the tag [6.2.3](https://github.com/STMicroelectronics/x-cube-ble1/tree/v6.2.3).
There you can find the code for [some peripheral profiles](https://github.com/STMicroelectronics/x-cube-ble1/tree/v6.2.3/Middlewares/ST/BlueNRG-MS/profiles/Peripheral/Src), included the [HID](https://github.com/STMicroelectronics/x-cube-ble1/tree/v6.2.3/Middlewares/ST/BlueNRG-MS/profiles/Peripheral/Src/hid_device).
Also, in [Projects ](https://github.com/STMicroelectronics/x-cube-ble1/tree/v6.2.3/Projects/NUCLEO-L476RG/Applications/Profiles_LowPower)folder you can find a sample application showing how to use them.

Please, note also that from tag 6.2.3 to 7.0.0 the ST BLE middleware code has not changed.

BR

**Comment by silviooliva** [comment]
Closing this issue, feel free to reopen it if you have further questions.

**Comment by westurner** [comment]
Thanks!
